/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class SIDAudioProcessorEditor  : public gin::GinAudioProcessorEditor
{
public:
    SIDAudioProcessorEditor (SIDAudioProcessor&);
    ~SIDAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;
    void paint (Graphics& g) override;

    SIDAudioProcessor& proc;
    
    gin::TriggeredScope scope {proc.fifo};
    Image logo;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SIDAudioProcessorEditor)
};

