/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "BinaryData.h"

//==============================================================================
SIDAudioProcessorEditor::SIDAudioProcessorEditor (SIDAudioProcessor& p)
    : slAudioProcessorEditor (p, 60, 100), processor (p)
{
    additionalProgramming = "Dag Lem";
    
    using AP = SIDAudioProcessor;
    
    logo = ImageFileFormat::loadFrom (BinaryData::logo_png, BinaryData::logo_pngSize);
    
    for (slParameter* pp : p.getPluginParameters())
    {
        ParamComponent* c;
        
        if (pp->getUid().contains ("tune") || pp->getUid().contains ("fine"))
            c = new Knob (pp, true);
        else if (pp->getUid() == AP::paramWave1 || pp->getUid() == AP::paramWave2 || pp->getUid() == AP::paramWave3)
            c = new Select (pp);
        else
            c = pp->isOnOff() ? (ParamComponent*)new Switch (pp) : (ParamComponent*)new Knob (pp);
        
        addAndMakeVisible (c);
        controls.add (c);
    }
    
    addAndMakeVisible (&scope);
    
    setGridSize (17, 3);
    
    scope.setNumSamplesPerPixel (2);
    scope.setVerticalZoomFactor (3.0f);

    p.setEditor (this);
}

SIDAudioProcessorEditor::~SIDAudioProcessorEditor()
{
    p.setEditor (nullptr);
}

//==============================================================================
void SIDAudioProcessorEditor::paint (Graphics& g)
{
    slAudioProcessorEditor::paint (g);
        
    g.drawImageAt (logo, getWidth() / 2 - logo.getWidth() / 2, 0);
}

void SIDAudioProcessorEditor::resized()
{
    using AP = SIDAudioProcessor;
    
    slAudioProcessorEditor::resized();
    
    Rectangle<int> r = getControlsArea();
    
    int idx = 0;
    Rectangle<int> rc;
    for (slParameter* pp : processor.getPluginParameters())
    {
        if (idx < 30)
        {
            if (idx % 10 == 8)
            {
                rc = getGridArea (idx % 10, idx / 10);
                componentForId (pp->getUid())->setBounds (rc.removeFromTop (rc.getHeight() / 2).translated (0, 7));
            }
            else if (idx % 10 == 9)
            {
                componentForId (pp->getUid())->setBounds (rc);
            }
            else
            {
                componentForId (pp->getUid())->setBounds (getGridArea (idx % 10, idx / 10));
            }
        }
        else
        {
            componentForId (pp->getUid())->setBounds (getGridArea (14 + (idx - 30) % 3, (idx - 30) / 3));
        }

        idx++;
    }
    
    rc = getGridArea (0, 2);
    componentForId (AP::paramWave3)->setBounds (rc.removeFromTop (rc.getHeight() / 2).translated (0, 7));
    componentForId (AP::paramOutput3)->setBounds (rc);

    scope.setBounds (getGridArea (9, 0, 5, 3).reduced (5));
}
