/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#pragma once

#include <JuceHeader.h>
#include "PluginProcessor.h"

//==============================================================================
/**
*/
class SIDAudioProcessorEditor  : public gin::ProcessorEditor
{
public:
    SIDAudioProcessorEditor (SIDAudioProcessor&);
    ~SIDAudioProcessorEditor() override;

    //==============================================================================
    void resized() override;
    void paint (Graphics& g) override;

    SIDAudioProcessor& sidProc;
    
    gin::TriggeredScope scope {sidProc.fifo};
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SIDAudioProcessorEditor)
};

